{% set version = "1.4.0rc2" %}
{% set org = "cyclus" %}
{% set branch = "1.4.0-rc2" %}
{% set sha256 = "06bcd127e5e558af94f66302655cb50a224be77fd9f52e32bb8acea9b2116292" %}
{% set variant = "openblas" %}

package:
  name: cycamore
  version: {{ version }}

source:
  fn: cycamore-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/cycamore/archive/{{ branch }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or not py35]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - toolchain
    - python
    - cmake
    - pkg-config
    - cyclus
  run:
    - cyclus

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The Cyclus additional modules repository."

extra:
  recipe-maintainers:
    - scopatz
