{% set version = "1.4.0" %}
{% set org = "cyclus" %}
{% set branch = "master" %}
{% set sha256 = "aebdbf3b4b4aa5eff09612e5de559b1fdc9458f2ae0d521741eb7312e581ee1b" %}
{% set variant = "openblas" %}

package:
  name: cycamore
  version: {{ version }}

source:
  fn: cycamore-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/cycamore/archive/{{ branch }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or not py35]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - toolchain
    - python
    - cmake
    - pkg-config
    - cyclus
  run:
    - cyclus

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The Cyclus additional modules repository."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - BaaaaaM
