travis:
  secure:
    BINSTAR_TOKEN: hyErCdZ+0yVyKl8g5OKeFCIHmM5bsyzsMiUxRIAmlx9nlXd9GXCL7cxuu4N1LnodOiUdrO0BXSMSnTAuPdcni9QW8Vw0r/1XQyytYAqRJqKlLvmQKAG/NwUBS+xv+axl4+hLq7LsId1PcFekRNlAJ8WBH7hspQnlPQ54YYgx+U6+YIyPgNG1AsVqJHuJfz3xoh+wb++9HNi2u5CSyT2bzHc1T6+vOsqnpgedwdry77MsusY39QXhrJsaQGsQ9ZvwoWZOn3XhQczfky2i5qW7RXTTHJ+5LiW1XeQZLNXpplt6jaqCVHxGjbooPDzXJvRjnchB+u6NHlfoECXQafrgOOMcMfuzLlxsB8amy8fgwq7N30rTBEsj20kYSU/6ApZ7BflnErR8h6vgbAg2wY5ii9XitNFaJxYfLhadjplClSb2qYP4PnG1RTobpTcxFEAwFmTxXnVOrjz86ha2nSUZANMeZc4ifybz/mD0i/X4ye4YyXBogjFBBMRxZ7QZ3mYGikGJWreLPxhwK43B4618QldyNFJk5ByULu7IlGlHK+kCJmjfVLqIRXvEHK/062YkZQs1aeAIJjBYLGrKBHSFUGSvesNPsha0VSWdX71IoZjLNUVQrgity7Sawu/TYudDMt0atVLz3ge4JS3TpjnNrWXpDijVvu3V51EKSGTBTgA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
